
nslice_to_use: 3 # keep only these edge slices
dummy_run: True # this flag must be true if running with the dummy data, otherwise set to false
global_seed: 42 # random seed for reproducibility

# paste in your paths
paths:
  input_manifest: "config/input_dummy_test.txt"
  output_dir: "output_dummy"
  fs_container: null
  bind_container: null

automask:
  metrics_list:
    - sd

# keyword parameters for gp_minimize used in the optimization module
optim_gp_minimize:
  dimensions:
    - [0.01, 1.5] # scaling factor
    - [0.01, 6.0] # frequency gain factor
  x0: [0.1, 2.0] # initial guess for the optimization
  n_calls: 50 # number of optimization iterations (including initial points)
  n_initial_points: 10 # number of initial random points to sample before starting the optimization
  initial_point_generator: "lhs" # method for generating initial random points
  acq_optimizer: "lbfgs" # method for optimizing the acquisition function
  acq_func: "EI" # acquisition function to use

optim:
  min_num_windows: 3
  power_factor: 2.0
  v_base_multiplier: 0.5

# parameters related to neural network training
train:
  train_epochs: 5000 # max epochs for training, but early stopping is used so it may stop earlier
  train_batch_size: 256
  train_lr: "1e-5"

# different argument sets to pass to training module
train_configs:
  train_base: "--batch 256 --lr 0.001  --noise_method none --lambda_phys 0.5"

# parameters for the synthetic dataset generation
synthetic:
  num_samples: 1000 # total number of synthetic data samples
  num_batches: 10 # number of subdivisions for splitting computations
  areamode: 'straight_tube' # options are ['straight_tube', 'collection']
  jitter_lb: 0.9 # lower bound for random jittering of optimization parameters to generate synthetic data for training
  jitter_ub: 1.1 # lower bound for random jittering of optimization parameters to generate synthetic data for training

# parameters used in the fMRI acquisition protocol
scan_param:
  slice_width: 0.25 # cm
  repetition_time: 0.378 # seconds
  echo_time: 0.031 # seconds
  flip_angle: 37 # degrees
  t1_time: 4 # T1 relaxation time for CSF [seconds]
  t2_time: 1.5 # T2 relaxation time for CSF [seconds]
  num_slice: 20 # total number of slices acquired
  num_pulse: 300 # number of simulated repetition cycles
  num_pulse_baseline_offset: 20 # number of initial pulses to discard
  MBF: 4 # multiband factor, i.e. how many slices are acquired simultaneously
  alpha_list: # the slice RF excitation timings
    - 0
    - 0.215
    - 0.0725
    - 0.2875
    - 0.145
    - 0
    - 0.215
    - 0.0725
    - 0.2875
    - 0.145
    - 0
    - 0.215
    - 0.0725
    - 0.2875
    - 0.145
    - 0
    - 0.215
    - 0.0725
    - 0.2875
    - 0.145

resources:

  threads_high: 100
  threads_low: 10

  # resources for running in SLURM. Ignore if running locally
  automask:
    runtime: 120
    nodes: 1
    cpus: 1
    mem_mb: 24000
  noise:
    runtime: 30
    nodes: 1
    cpus: 1
    mem_mb: 20000
  area:
    runtime: 120
    nodes: 1
    cpus: 1
    mem_mb: 16000
  optim:
    runtime: 320
    nodes: 1
    cpus: 20
    mem_mb: 42000
  aggregate_noise:
    runtime: 20
    nodes: 1
    cpus: 1
    mem_mb: 20000
  aggregate_area:
    runtime: 15
    mem_mb: 4000
  aggregate_optim:
    runtime: 120
    nodes: 1
    cpus: 20
    mem_mb: 64000
  synthdata_sampling:
    runtime: 120
    nodes: 1
    cpus: 1
    mem_mb: 8000
  synthdata_sort:
    runtime: 60
    nodes: 1
    cpus: 1
    mem_mb: 32000
  synthdata_simulate:
    runtime: 240
    nodes: 1
    cpus: 5
    mem_mb: 16000
  synthdata_combine:
    runtime: 240
    nodes: 1
    cpus: 64
    mem_mb: 100000
  train_surrogate:
    runtime: 360
    nodes: 1
    cpus: 4
    mem_mb: 64000
    gpus: 4
  train_model:
    runtime: 240
    nodes: 1
    cpus: 1
    mem_mb: 64000
    gpus: 1
  evaluate:
    runtime: 240
    nodes: 1
    cpus: 1
    mem_mb: 24000